services:
  # Frontend Static Site
  - type: web
    name: ai-receipt-frontend
    env: static
    rootDir: .
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend Web Service
  - type: web
    name: ai-receipt-backend
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start