services:
  - type: web
    name: ai-receipt-app
    env: static
    rootDir: .
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html